(hoilic () (test) 
  (load "cell.hic")
  (def (test) 
    (bindseq ((c1 (seq (println "Creating cell c1 via (cell 17)")
 		       (cell 17)))
	      (c2 (seq (println "Creating cell c2 via (cell 42)")
		       (cell 42)))
	       (printcells (fun ()
			     (seq (print "Value of (^ c1) is now: ")
				  (println (^ c1))
				  (print "Value of (^ c2) is now: ")
				  (println (^ c2))))))
      (seq (printcells)
	   (print "Value of (:= c1 (* 2 (^ c1))) is: ")
	   (println (:= c1 (* 2 (^ c1))))
	   (printcells)
	   (print "Value of (:= c1 (:= c2 (^ c1))) is: ")
	   (println (:= c1 (:= c2 (^ c1))))
           (printcells)))))
